<a href="https://colab.research.google.com/github/m37335/kanagawa-exam/blob/master/util_sentenceAndMaskedword.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
dataset_df = pd.read_csv('https://raw.githubusercontent.com/m37335/kanagawa-exam/master/data/textbook_sentence_maskedword_df-check.csv')

In [2]:
dataset_df

      Unnamed: 0    id textBook  grade  articleId  ...   21   22   23   24   25
0              0    92       NH      1          6  ...  NaN  NaN  NaN  NaN  NaN
1              1  1255       NH      3         11  ...  NaN  NaN  NaN  NaN  NaN
2              2  1088       NH      3          3  ...  NaN  NaN  NaN  NaN  NaN
3              3   111       NH      1          6  ...  NaN  NaN  NaN  NaN  NaN
4              4   442       NH      1         32  ...  NaN  NaN  NaN  NaN  NaN
...          ...   ...      ...    ...        ...  ...  ...  ...  ...  ...  ...
6416        6416   297       NH      1         21  ...  NaN  NaN  NaN  NaN  NaN
6417        6417  1073       NH      3          2  ...  NaN  NaN  NaN  NaN  NaN
6418        6418  1233       NH      3         10  ...  NaN  NaN  NaN  NaN  NaN
6419        6419  1348       NH      3         15  ...  NaN  NaN  NaN  NaN  NaN
6420        6420  1549       NH      3         22  ...  NaN  NaN  NaN  NaN  NaN

[6421 rows x 36 columns]

In [8]:
sentences = dataset_df.sentence.values.tolist()
masked_words = dataset_df.masked_Word.values.tolist()

print(sentences[0:2])
print(sentences[0].replace('band', '[MASK]'))

['I play the guitar in a band.', 'We could see a band of bright green lights in the sky.']
I play the guitar in a [MASK].

In [14]:
sentence_list = []
for sentence, masked_word in zip(sentences, masked_words):
  sentence_list.append(sentence.replace(masked_word, '[MASK]'))

In [16]:
sentence_list[0:9]

['I play the guitar in a [MASK].',
 'We could see a [MASK] of bright green lights in the sky.',
 "It's made from [MASK].",
 'I want a black [MASK].',
 'Take off your clothes, and Put salt and vinegar on your [MASK]…',
 'They had burns all over their [MASK].',
 'On the morning of that day, a big [MASK] fell on the city of Hiroshima.',
 'I was looking for my pencil [MASK].',
 'In [MASK] of a fire, go outside.']

In [18]:
df = pd.DataFrame(sentence_list,
                  columns=['sentence'])

In [19]:
df['masked_word'] = masked_words

In [20]:
df

                                               sentence  masked_word
0                        I play the guitar in a [MASK].         band
1     We could see a [MASK] of bright green lights i...         band
2                                It's made from [MASK].         beef
3                                I want a black [MASK].         belt
4     Take off your clothes, and Put salt and vinega...       bodies
...                                                 ...          ...
6416     They’re watching henmen, a [MASK] Chinese art.  traditional
6417  I think manga and anime will be [MASK] Japanes...  traditional
6418   Kyoto is an old city with many [MASK] buildings.  traditional
6419     Feel the [MASK] rhythms created by technology.  traditional
6420  Even the Inuit are losing their [MASK] way of ...  traditional

[6421 rows x 2 columns]

In [21]:
# CSVで出力し、ダウンロード
from google.colab import files
filename =  "textbook_sentence_maskedword_df.csv"
df.to_csv(filename, encoding = 'utf-8-sig') 
files.download(filename)